name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot(s)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Browser name and version
      placeholder: |
         - Browser [e.g. Chrome, Safari, Firefox]
         - Version [e.g. 96.0.3]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: If applicable, add screenshots of the console log (<kbd>F12</kbd> or <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd>)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Notes
      description: Add any other context about the problem that doesn't fit into any category here
    validations:
      required: false